ALTER TABLE exam_sessions
    ADD COLUMN grade_type VARCHAR(50) NOT NULL;

ALTER TABLE exam_sessions
    ADD CONSTRAINT chk_grade_type
        CHECK (grade_type IN (
            'TOAN',
            'LY_HOA_SINH_DIA',
            'SU_GDKTPL_TIN_CONG_NGHE',
            'NGOAI_NGU'
        ));

CREATE TABLE public.answer_keys (
    id BIGINT NOT NULL,
    paper_code VARCHAR(50) NOT NULL,
    exam_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.answer_keys
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_keys_id_seq
    START WITH 1
    INCREMENT BY 1
);

ALTER TABLE ONLY public.answer_keys
    ADD CONSTRAINT answer_keys_pkey PRIMARY KEY (id);

ALTER TABLE public.answer_keys
    ADD CONSTRAINT fk_answer_keys_exam
        FOREIGN KEY (exam_id)
            REFERENCES public.exams(id)
            ON DELETE CASCADE;

ALTER TABLE public.answer_keys
    ADD CONSTRAINT uk_answer_keys_exam_paper
        UNIQUE (exam_id, paper_code);

CREATE TABLE public.answer_key_details (
    id BIGINT NOT NULL,
    question_number INTEGER NOT NULL,
    part_type VARCHAR(50) NOT NULL,
    sub_question VARCHAR(10),
    correct_value VARCHAR(50) NOT NULL,
    answer_key_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.answer_key_details
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_key_details_id_seq
    START WITH 1
    INCREMENT BY 1
);

ALTER TABLE ONLY public.answer_key_details
    ADD CONSTRAINT answer_key_details_pkey PRIMARY KEY (id);

ALTER TABLE public.answer_key_details
    ADD CONSTRAINT fk_answer_key_details_answer_key
        FOREIGN KEY (answer_key_id)
            REFERENCES public.answer_keys(id)
            ON DELETE CASCADE;

ALTER TABLE public.answer_key_details
    ADD CONSTRAINT uk_answer_detail
        UNIQUE (answer_key_id, question_number, sub_question);

ALTER TABLE public.answer_key_details
    ADD CONSTRAINT chk_part_type
        CHECK (part_type IN (
            'PART1',
            'PART2',
            'PART3'
        ));