-- ============================================================
-- Bảng quizzes: bài test
-- ============================================================
CREATE TABLE public.quizzes (
    id               BIGINT NOT NULL,
    quiz_code        VARCHAR(20) UNIQUE NOT NULL,
    title            VARCHAR(255) NOT NULL,
    description      TEXT,
    duration_minutes INTEGER,
    max_attempts     INTEGER,
    total_score      DOUBLE PRECISION,
    start_time       TIMESTAMP WITHOUT TIME ZONE,
    end_time         TIMESTAMP WITHOUT TIME ZONE,
    class_id         BIGINT,
    creator_id       BIGINT NOT NULL,
    allow_review     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE public.quizzes
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.quizzes_id_seq
        START WITH 1
        INCREMENT BY 1
    );

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT quizzes_pkey PRIMARY KEY (id);

ALTER TABLE public.quizzes
    ADD CONSTRAINT fk_quizzes_creator
        FOREIGN KEY (creator_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

ALTER TABLE public.quizzes
    ADD CONSTRAINT fk_quizzes_class
        FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;

ALTER TABLE public.quizzes
    ADD CONSTRAINT chk_quizzes_time_window
        CHECK (
            start_time IS NULL
                OR end_time IS NULL
                OR end_time > start_time
        );

-- ============================================================
-- Bảng questions: câu hỏi
-- (SHORT_ANSWER không dùng correct_answer nữa – dùng bảng short_answer_options)
-- ============================================================
CREATE TABLE public.questions (
    id                   BIGINT NOT NULL,
    content              TEXT NOT NULL,
    question_type        VARCHAR(20) NOT NULL
        CHECK (question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','SHORT_ANSWER')),
    score                DOUBLE PRECISION,
    media_object_key     VARCHAR(500),
    media_content_type   VARCHAR(150),
    quiz_id              BIGINT,
    creator_id           BIGINT,
    group_question_id    BIGINT,
    category_question_id BIGINT,
    created_at           TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.questions
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.questions_id_seq
        START WITH 1
        INCREMENT BY 1
    );

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);

ALTER TABLE public.questions
    ADD CONSTRAINT fk_questions_quiz
        FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id) ON DELETE CASCADE;

ALTER TABLE public.questions
    ADD CONSTRAINT fk_questions_creator
        FOREIGN KEY (creator_id) REFERENCES public.accounts(id) ON DELETE CASCADE ;

ALTER TABLE public.questions
    ADD CONSTRAINT fk_questions_group
        FOREIGN KEY (group_question_id) REFERENCES public.group_questions(id) ON DELETE SET NULL;

ALTER TABLE public.questions
    ADD CONSTRAINT fk_questions_category
        FOREIGN KEY (category_question_id) REFERENCES public.category_questions(id) ON DELETE SET NULL;

-- ============================================================
-- Bảng question_options: đáp án trắc nghiệm (SINGLE_CHOICE / MULTIPLE_CHOICE)
-- Mỗi option gồm label (A/B/C/D) và text nội dung
-- ============================================================
CREATE TABLE public.question_options (
    id          BIGINT NOT NULL,
    option_text TEXT         NOT NULL,
    is_correct  BOOLEAN      NOT NULL DEFAULT FALSE,
    question_id BIGINT       NOT NULL,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.question_options
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.question_options_id_seq
        START WITH 1
        INCREMENT BY 1
    );

ALTER TABLE ONLY public.question_options
    ADD CONSTRAINT question_options_pkey PRIMARY KEY (id);

ALTER TABLE public.question_options
    ADD CONSTRAINT fk_options_question
        FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE;

-- ============================================================
-- Bảng short_answer_options: các đáp án đúng cho câu trả lời ngắn
-- Cho phép nhiều đáp án đúng (không phân biệt hoa/thường khi so sánh)
-- ============================================================
CREATE TABLE public.short_answer_options (
    id          BIGINT NOT NULL,
    answer_text TEXT    NOT NULL,
    question_id BIGINT  NOT NULL,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.short_answer_options
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.short_answer_options_id_seq
        START WITH 1
        INCREMENT BY 1
    );

ALTER TABLE ONLY public.short_answer_options
    ADD CONSTRAINT short_answer_options_pkey PRIMARY KEY (id);

ALTER TABLE public.short_answer_options
    ADD CONSTRAINT fk_short_answer_question
        FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE;

ALTER TABLE public.short_answer_options
    ADD CONSTRAINT uq_short_answer_per_question
        UNIQUE (question_id, answer_text);
