-- ============================================================
-- Bảng category_questions: danh mục câu hỏi
-- ============================================================
CREATE TABLE public.category_questions (
    id         BIGINT NOT NULL,
    name       VARCHAR(255) NOT NULL,
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.category_questions
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.category_questions_id_seq
        START WITH 1
        INCREMENT BY 1
    );

ALTER TABLE ONLY public.category_questions
    ADD CONSTRAINT category_questions_pkey PRIMARY KEY (id);

ALTER TABLE public.category_questions
    ADD CONSTRAINT fk_category_questions_creator
        FOREIGN KEY (creator_id)
            REFERENCES public.accounts(id)
            ON DELETE RESTRICT;

-- ============================================================
-- Bảng group_questions: nhóm câu hỏi (độc lập, không thuộc danh mục)
-- ============================================================
CREATE TABLE public.group_questions (
    id         BIGINT NOT NULL,
    name       VARCHAR(255) NOT NULL,
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.group_questions
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.group_questions_id_seq
        START WITH 1
        INCREMENT BY 1
    );

ALTER TABLE ONLY public.group_questions
    ADD CONSTRAINT group_questions_pkey PRIMARY KEY (id);

ALTER TABLE public.group_questions
    ADD CONSTRAINT fk_group_questions_creator
        FOREIGN KEY (creator_id)
            REFERENCES public.accounts(id)
            ON DELETE RESTRICT;
