-- ==============================
-- TABLE: exams
-- ==============================

CREATE TABLE public.exams (
    id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE ,
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Identity
ALTER TABLE public.exams
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_id_seq
    START WITH 1
    INCREMENT BY 1
);

-- Primary Key
ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pkey PRIMARY KEY (id);

-- Foreign Key -> accounts
ALTER TABLE public.exams
    ADD CONSTRAINT fk_exams_creator
        FOREIGN KEY (creator_id)
            REFERENCES public.accounts(id)
            ON DELETE CASCADE;