CREATE TABLE public.medias (
    id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    content_type VARCHAR(150) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Identity
ALTER TABLE public.medias
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medias_id_seq
    START WITH 1
    INCREMENT BY 1
);

-- Primary Key
ALTER TABLE ONLY public.medias
    ADD CONSTRAINT medias_pkey PRIMARY KEY (id);

-- Foreign key
ALTER TABLE public.medias
    ADD CONSTRAINT fk_medias_created_by
        FOREIGN KEY (created_by)
            REFERENCES public.accounts(id)
            ON DELETE RESTRICT;