CREATE TABLE public.classes (
    id BIGINT NOT NULL,
    class_code VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.classes
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);

ALTER TABLE public.classes
    ADD CONSTRAINT fk_classes_creator
        FOREIGN KEY (creator_id)
            REFERENCES public.accounts(id)
            ON DELETE CASCADE;

CREATE TABLE public.class_members (
    id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'APPROVED')),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.class_members
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT class_members_pkey PRIMARY KEY (id);

ALTER TABLE public.class_members
    ADD CONSTRAINT fk_class_members_class
        FOREIGN KEY (class_id)
            REFERENCES public.classes(id)
            ON DELETE CASCADE;

ALTER TABLE public.class_members
    ADD CONSTRAINT fk_class_members_account
        FOREIGN KEY (account_id)
            REFERENCES public.accounts(id)
            ON DELETE CASCADE;

ALTER TABLE public.class_members
    ADD CONSTRAINT uk_class_account UNIQUE (class_id, account_id);

-- ==============================
-- TABLE: documents
-- ==============================

CREATE TABLE public.documents (
    id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Identity
ALTER TABLE public.documents
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
);

-- Primary Key
ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

-- Foreign Key -> classes
ALTER TABLE public.documents
    ADD CONSTRAINT fk_documents_class
        FOREIGN KEY (class_id)
            REFERENCES public.classes(id)
            ON DELETE CASCADE;

-- ==============================
-- TABLE: document_details
-- ==============================

CREATE TABLE public.document_details (
    id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    content_type VARCHAR(150) NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.document_details
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_details_id_seq
    START WITH 1
    INCREMENT BY 1
);

ALTER TABLE ONLY public.document_details
    ADD CONSTRAINT document_details_pkey PRIMARY KEY (id);

ALTER TABLE public.document_details
    ADD CONSTRAINT fk_document_details_document
        FOREIGN KEY (document_id)
            REFERENCES public.documents(id)
            ON DELETE CASCADE;

