CREATE TABLE public.candidates (
    id BIGINT NOT NULL,
    exam_id BIGINT NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    candidate_number VARCHAR(50) NOT NULL, -- số báo danh
    exam_room VARCHAR(50) NOT NULL ,                 -- phòng thi
    note TEXT,
    class_name VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(20),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.candidates
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.candidates_id_seq
    START WITH 1
    INCREMENT BY 1
);

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT fk_candidate_exam
    FOREIGN KEY (exam_id)
    REFERENCES public.exams(id)
    ON DELETE CASCADE;

ALTER TABLE public.candidates
    ADD CONSTRAINT uk_exam_candidate_number
        UNIQUE (exam_id, candidate_number);