CREATE TABLE public.exam_sessions (
    id BIGINT NOT NULL,
    exam_id BIGINT NOT NULL,
    session_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Identity
ALTER TABLE public.exam_sessions
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
);

-- Primary Key
ALTER TABLE ONLY public.exam_sessions
    ADD CONSTRAINT exam_sessions_pkey PRIMARY KEY (id);

-- Foreign Key -> exams
ALTER TABLE public.exam_sessions
    ADD CONSTRAINT fk_exam_sessions_exam
        FOREIGN KEY (exam_id)
            REFERENCES public.exams(id)
            ON DELETE CASCADE;

ALTER TABLE public.exam_sessions
    ADD CONSTRAINT uk_exam_session_name
        UNIQUE (exam_id, session_name);